-- MySQL Script generated by MySQL Workbench
-- Fri Jun 30 22:55:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_oportunidades_online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_oportunidades_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_oportunidades_online` DEFAULT CHARACTER SET utf8 ;
USE `bd_oportunidades_online` ;

-- -----------------------------------------------------
-- Table `bd_oportunidades_online`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_oportunidades_online`.`Comentario` (
  `idComentario` INT NOT NULL,
  `horaComentario` DATETIME NULL,
  `texto` VARCHAR(45) NULL,
  `Procurante_idProcurante` INT NOT NULL,
  `Procurante_Perfil_idPerfil` INT NOT NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  `Empresa_Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idComentario`, `Procurante_idProcurante`, `Procurante_Perfil_idPerfil`, `Empresa_idEmpresa`, `Empresa_Perfil_idPerfil`),
  INDEX `fk_Comentario_Procurante1_idx` (`Procurante_idProcurante` ASC, `Procurante_Perfil_idPerfil` ASC) VISIBLE,
  INDEX `fk_Comentario_Empresa1_idx` (`Empresa_idEmpresa` ASC, `Empresa_Perfil_idPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_Comentario_Procurante1`
    FOREIGN KEY (`Procurante_idProcurante` , `Procurante_Perfil_idPerfil`)
    REFERENCES `bd_oportunidades_online`.`Procurante` (`idProcurante` , `Perfil_idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa` , `Empresa_Perfil_idPerfil`)
    REFERENCES `bd_oportunidades_online`.`Empresa` (`idEmpresa` , `Perfil_idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_oportunidades_online`.`Conversa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_oportunidades_online`.`Conversa` (
  `idConversa` INT NOT NULL,
  `horaConversa` DATETIME NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  `Empresa_Perfil_idPerfil` INT NOT NULL,
  `Procurante_idProcurante` INT NOT NULL,
  `Procurante_Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idConversa`, `Empresa_idEmpresa`, `Empresa_Perfil_idPerfil`, `Procurante_idProcurante`, `Procurante_Perfil_idPerfil`),
  INDEX `fk_Conversa_Empresa1_idx` (`Empresa_idEmpresa` ASC, `Empresa_Perfil_idPerfil` ASC) VISIBLE,
  INDEX `fk_Conversa_Procurante1_idx` (`Procurante_idProcurante` ASC, `Procurante_Perfil_idPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_Conversa_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa` , `Empresa_Perfil_idPerfil`)
    REFERENCES `bd_oportunidades_online`.`Empresa` (`idEmpresa` , `Perfil_idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conversa_Procurante1`
    FOREIGN KEY (`Procurante_idProcurante` , `Procurante_Perfil_idPerfil`)
    REFERENCES `bd_oportunidades_online`.`Procurante` (`idProcurante` , `Perfil_idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_oportunidades_online`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_oportunidades_online`.`Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cnpj` CHAR(14) NOT NULL,
  `telefone` CHAR(11) NULL,
  `senha` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` CHAR(2) NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero` CHAR(5) NULL,
  `Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idEmpresa`, `Perfil_idPerfil`),
  INDEX `fk_Empresa_Perfil1_idx` (`Perfil_idPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_Empresa_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil`)
    REFERENCES `bd_oportunidades_online`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_oportunidades_online`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_oportunidades_online`.`Perfil` (
  `idPerfil` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `imagem` LONGBLOB NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_oportunidades_online`.`Procurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_oportunidades_online`.`Procurante` (
  `idProcurante` INT NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `telefone` CHAR(11) NULL,
  `senha` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` CHAR(2) NULL,
  `logradouro` VARCHAR(45) NULL,
  `interesse` VARCHAR(45) NULL,
  `pretencaoSalarial` DECIMAL(10,2) NULL,
  `experienciaProfissional` VARCHAR(45) NULL,
  `Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idProcurante`, `Perfil_idPerfil`),
  INDEX `fk_Procurante_Perfil1_idx` (`Perfil_idPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_Procurante_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil`)
    REFERENCES `bd_oportunidades_online`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_oportunidades_online`.`Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_oportunidades_online`.`Projeto` (
  `idProjeto` INT NOT NULL AUTO_INCREMENT,
  `tempoPrevisto` VARCHAR(45) NULL,
  `requerimentosProjeto` VARCHAR(45) NULL,
  `formacaoNecessaria` VARCHAR(45) NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  `salarioPretendido` DECIMAL(10,2) NULL,
  `Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idProjeto`, `Empresa_idEmpresa`, `Perfil_idPerfil`),
  INDEX `fk_Projeto_Empresa1_idx` (`Empresa_idEmpresa` ASC) VISIBLE,
  INDEX `fk_Projeto_Perfil1_idx` (`Perfil_idPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_Projeto_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `bd_oportunidades_online`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projeto_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil`)
    REFERENCES `bd_oportunidades_online`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_oportunidades_online`.`Vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_oportunidades_online`.`Vaga` (
  `idVaga` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `salarioPretendido` DECIMAL(10,2) NULL,
  `requerimentosVaga` VARCHAR(45) NULL,
  `formacaoNecessaria` VARCHAR(45) NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  `Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idVaga`, `Empresa_idEmpresa`, `Perfil_idPerfil`),
  INDEX `fk_Vaga_Empresa1_idx` (`Empresa_idEmpresa` ASC) VISIBLE,
  INDEX `fk_Vaga_Perfil1_idx` (`Perfil_idPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_Vaga_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `bd_oportunidades_online`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vaga_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil`)
    REFERENCES `bd_oportunidades_online`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
